### ISSUE TITLE
Linking error on Linux x86_64

### ISSUE THREAD

**Issue by aifia** [Sparrow-lang/sparrow#66]
Hello,

when I try to compile sparrow, the LLVM_6 branch, on linux x86_64 system with llvm version 6.0.0 I get compilation error:

> /bin/ld: /src/sparrow-0.11.35-20180425/build/bin/libSparrowFrontend.a(parserIf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
> /bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/SparrowCompiler/CMakeFiles/SparrowCompiler.dir/build.make:231: /src/sparrow-0.11.35~20180425/build/bin/SparrowCompiler] Error 1
> make[1]: *** [CMakeFiles/Makefile2:341: src/SparrowCompiler/CMakeFiles/SparrowCompiler.dir/all] Error 2
>  make: *** [Makefile:130: all] Error 2

I've noticed that 'Grammar/parserIf.ll' is being used to link libSparrowFrontend.a, which I presume is prebuilt. I wonder if it is possible to build parserIf.ll with '-fPIC' option so that I can build sparrow. I've tried adding '-fPIC' to CXXFLAGS and CMAKE_CXX_FLAGS build environments but it doesn't work at all.

**Comment by lucteo** [comment]
Hi aifia

LLVM_6 branch is not yet fully supported. Made a quick attempt to switch LLVM 5.0 to LLVM 6.0; compiled it on my mac, and it worked. Then I encountered some package problems on Travis-CI / Linux, so I paused the efforts.

Some background: Grammar code is written in Sparrow and the compiled into LLVM assembly (the .ll file). This will be compiled into an object file, and linked against libSparrowFrontend.a. This library is built from C++ code and this Sparrow code.

This code compiled fine on my Mac, so the error most probably comes from a tool configuration issue. Are you using clang 5/6 as your compiler?

Is there any particularly reason you want to try the LLVM_6 branch instead of master?

Best regards,
LucTeo

**Comment by aifia** [comment]
Hello LucTeo,

thank you for explaining to me the compiler internals. I wasn't able to compile sparrow on the master branch, since I got some errors, and I am using clang version 6.0.0, 'clan -v':

> clang version 6.0.0 (tags/RELEASE_600/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /bin
> Found candidate GCC installation: /bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.0
> Found candidate GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.0
> Selected GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.0
> Candidate multilib: .;@m64
> Selected multilib: .;@m64

I have limited possibilities to try the master branch on llvm 5.0.0. I am currently on vocation using a customized linux distro on a usb stick.

**Comment by lucteo** [comment]
Hi

Do you have the ability to try the docker version? (https://hub.docker.com/r/sparrowlang/sparrow/)

If not, I can start tomorrow to look again at clang-6 compilation. However, I'm afraid that you may need some extra packages to install, and probably to reconfigure clang not to use GCC tools.

**Comment by aifia** [comment]
I am working on the docker image right now, and I'll let you know how it goes. Thanks!

**Comment by aifia** [comment]
Hello, 

I have tried pulling sparrowlang/sparrow many times and I get: 
> unauthorized: authentication required

I'm out of ideas for now. I'll investigate more tomorrow.

**Comment by aifia** [comment]
I've downloaded binary packages of LLVM version 5.0.1 and tried building the master and got this error:

> /src/sparrow-0.11.35-20180425/src/Nest/src/Api/NodeKindRegistrar.c:15:29: error: variably modified '_allNodeKinds' at file scope
>  struct _NodeKindDescription _allNodeKinds[_maxNodeKinds];
>                              ^~~~~~~~~~~~~
> make[2]: *** [src/Nest/CMakeFiles/Nest.dir/build.make:183: src/Nest/CMakeFiles/Nest.dir/src/Api/NodeKindRegistrar.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:118: src/Nest/CMakeFiles/Nest.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs...

Build configuration: 
```
    cd $BLD_DIR

    cmake $SRC_DIR \
        -DCMAKE_INSTALL_PREFIX=$prefix \
        -DCMAKE_BUILD_TYPE=Release \
        -DLLVM_DIR=/home/ahc/LLVM-5.0.1/usr/lib/cmake/llvm
    make
    make DESTDIR=$PKG_DIR install
```

**Comment by aifia** [comment]
Hello,

I am running a custom linux distribution built from scratch. I think I have to configure iptables and docker in order to get a good result. "update-alternatives" is a ubuntu/debian specific command, so I did not try that. I'll be able to use the desktop instead of using a usb stick, so I might get different results, plus I have a slow internet speed right now, so I will have access to faster internet after the vocation ends. Thank you for your help and best wishes!

**Comment by lucteo** [comment]
I'm trying now to build on ArchLinux. It's so damn hard. With LLVM breaking compatibility with each version, with everything being so up to date, it's hard to mix everything into something that just works. This is definitely something that won't scale up. I'll keep trying...

**Comment by lucteo** [comment]
Found the source of the error. For some reason, parserIf.o (compiled from parserIf.llvm) is not linked into libSparrowFrontend. Therefore, some symbols are missing at the final link. And the linker is dummy enough not to know about this, and complains about "-fPIC" error.

Looking at parserIf.o, it seems that:
* it is generated in the wrong location (in the src directory tree, not in build)
* it has a wrong format

Keep looking at it.

**Comment by lucteo** [comment]
Finally made it work on arch linux. Please see https://github.com/Sparrow-lang/sparrow/commit/6d5e287c31e7282c6bcd91f0cd11822182554be9

The patch still needs to be cleaned up, and the branch merged to master

**Comment by lucteo** [comment]
Thank you Ali!

Please send me notes on your experience with Sparrow, what are the problems you encountered, and what are the things you are interested on how they can be solved in Sparrow, etc. I would really like to make sure that the language is flexible enough to nicely accommodate the needs of all its users.

FYI: https://twitter.com/sparrow_lang/status/990539335207456768
